hooks:
  - hooks/debug.py
  # https://squidfunk.github.io/mkdocs-material/reference/
site_name: nhc mkdocss
site_url: https://opennhc.github.io/mkdocs-githubio
plugins:
  - search
  - meta
  - blog
  - tags
theme:
  name: material
  language: en
  custom_dir: overrides
  icon:
#    logo: fontawesome/solid/user-shield
    search: material/text-search
  logo: assets/nhc-black.png
  favicon: assets/nhc-white.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: nhc-l #slate
      toggle:
       icon: material/lightbulb
       name: Light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: nhc-d #slate
      toggle:
        icon: material/lightbulb-outline
        name: Dark mode
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer
    - announce.dismiss
    - navigation.tracking
    - navigation.instant
#    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#  https://pygments.org/docs/lexers/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
# Tabs https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.tabbed:
      alternate_style: true
# admonition https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
# diagrams https://squidfunk.github.io/mkdocs-material/reference/diagrams/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
#  - material.extensions.preview:
#      configurations:
#        - targets:
#            include:
#              - howtos/index.md
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jsanchezperez
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
#  alternate:
#    - name: English
#      link: /en/
#      lang: en
#    - name: Spanish
#      link: /es/
#      lang: es
copyright: Copyright &copy; 2025 JSanchez (nhc org)