authors:
  jsanchez:
    name: Jorge Sanchez
    description: Creator
    avatar: https://github.com/jsanhc.png
  nhc:
    name: No Hay Color
    description: Creator
    avatar: https://github.com/opennhc.png